// ADONI GENERATED KNOWLEDGE BASE
// AUTO-GENERATED by npm run adoni:train — do not edit manually
// Generated: 2026-04-05T00:00:00.000Z (initial stub — run adoni:train to populate)

export const GENERATED_KNOWLEDGE = {
  platform: "Run npm run adoni:train to populate platform stats.",
  apiRoutes: "Run npm run adoni:train to index API routes.",
  featureChecklist: "Run npm run adoni:train to load feature checklist.",
  recentFixes: "Run npm run adoni:train to load recent fixes.",
  electionLaw: "Run npm run adoni:train to load election law.",
  generatedAt: "2026-04-05T00:00:00.000Z",
};

export function getFullKnowledge(): string {
  return [
    "=== PLATFORM STATUS ===",
    GENERATED_KNOWLEDGE.platform,
    "=== API ROUTES ===",
    GENERATED_KNOWLEDGE.apiRoutes,
    "=== FEATURE STATUS ===",
    GENERATED_KNOWLEDGE.featureChecklist,
    "=== RECENT FIXES ===",
    GENERATED_KNOWLEDGE.recentFixes,
    "=== ELECTION LAW ===",
    GENERATED_KNOWLEDGE.electionLaw,
  ].join("\n\n");
}
