/** Master permission definitions and default role templates */

import type { PermissionGroup, RoleTemplate } from "./types";

// ─── Permission Groups ───────────────────────────────────────────────────────

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    id: "contacts",
    label: "Contacts & Field",
    icon: "Users",
    permissions: [
      { key: "contacts:read", label: "View contacts", description: "View contact list, details, and timelines" },
      { key: "contacts:write", label: "Edit contacts", description: "Create and edit contact records" },
      { key: "contacts:delete", label: "Delete contacts", description: "Remove contacts from the database", sensitive: true },
      { key: "contacts:export", label: "Export contacts", description: "Download contact data as CSV/Excel", sensitive: true, minTrust: 2 },
      { key: "contacts:import", label: "Import contacts", description: "Upload and import voter lists" },
      { key: "canvassing:read", label: "View canvassing", description: "View walk lists, turf maps, and canvass data" },
      { key: "canvassing:write", label: "Log canvassing", description: "Record door knocks and canvass results" },
      { key: "canvassing:manage", label: "Manage canvassing", description: "Create turfs, assign volunteers to walks", sensitive: true },
      { key: "gotv:read", label: "View GOTV", description: "View priority lists and voted tracker" },
      { key: "gotv:write", label: "Update GOTV", description: "Upload voted lists, run strike-off" },
      { key: "gotv:manage", label: "GOTV command", description: "Access election day command centre", sensitive: true },
    ],
  },
  {
    id: "team",
    label: "Team & Volunteers",
    icon: "UserCog",
    permissions: [
      { key: "volunteers:read", label: "View volunteers", description: "View volunteer list, profiles, and availability" },
      { key: "volunteers:write", label: "Manage volunteers", description: "Edit profiles, create shifts, log hours" },
      { key: "volunteers:manage", label: "Administer volunteers", description: "Approve/deactivate volunteers, manage groups", sensitive: true },
      { key: "team:read", label: "View team", description: "See team members and their roles" },
      { key: "team:manage", label: "Manage team", description: "Invite/remove members, change roles and permissions", sensitive: true },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    icon: "DollarSign",
    permissions: [
      { key: "donations:read", label: "View donations", description: "View donation records and totals" },
      { key: "donations:write", label: "Log donations", description: "Record donations and generate receipts" },
      { key: "budget:read", label: "View budget", description: "View budget items and spending" },
      { key: "budget:write", label: "Edit budget", description: "Add/edit budget items and expenses" },
      { key: "budget:manage", label: "Manage finances", description: "Set spending limits, approve expenses, financial compliance", sensitive: true, minTrust: 3 },
    ],
  },
  {
    id: "communications",
    label: "Communications",
    icon: "Mail",
    permissions: [
      { key: "email:read", label: "View emails", description: "View sent email campaigns and drafts" },
      { key: "email:write", label: "Send emails", description: "Draft and send email campaigns" },
      { key: "sms:read", label: "View SMS", description: "View sent SMS campaigns" },
      { key: "sms:write", label: "Send SMS", description: "Send SMS/text blasts", sensitive: true },
      { key: "social:read", label: "View social", description: "View social media posts and mentions" },
      { key: "social:write", label: "Manage social", description: "Create and schedule social media posts" },
      { key: "notifications:write", label: "Send notifications", description: "Send push notifications to supporters" },
    ],
  },
  {
    id: "operations",
    label: "Campaign Operations",
    icon: "Target",
    permissions: [
      { key: "signs:read", label: "View signs", description: "View sign requests and map" },
      { key: "signs:write", label: "Manage signs", description: "Create/update sign lifecycle" },
      { key: "events:read", label: "View events", description: "View events and RSVPs" },
      { key: "events:write", label: "Manage events", description: "Create and manage events" },
      { key: "tasks:read", label: "View tasks", description: "View assigned tasks" },
      { key: "tasks:write", label: "Manage tasks", description: "Create and assign tasks" },
      { key: "polls:read", label: "View polls", description: "View poll results" },
      { key: "polls:write", label: "Create polls", description: "Create and manage polls" },
    ],
  },
  {
    id: "analytics",
    label: "Analytics & Intelligence",
    icon: "BarChart3",
    permissions: [
      { key: "analytics:read", label: "View analytics", description: "View campaign analytics dashboards" },
      { key: "analytics:export", label: "Export analytics", description: "Download analytics reports", sensitive: true, minTrust: 2 },
      { key: "intelligence:read", label: "View intelligence", description: "View opponent intel and research" },
      { key: "intelligence:write", label: "Edit intelligence", description: "Add opponent intel entries" },
    ],
  },
  {
    id: "admin",
    label: "Administration",
    icon: "Settings",
    permissions: [
      { key: "settings:read", label: "View settings", description: "View campaign configuration" },
      { key: "settings:write", label: "Edit settings", description: "Change campaign settings, brand kit", sensitive: true },
      { key: "billing:manage", label: "Manage billing", description: "Subscription, invoices, payment methods", sensitive: true, minTrust: 4 },
      { key: "security:manage", label: "Security admin", description: "2FA enforcement, security audit log, IP restrictions", sensitive: true, minTrust: 4 },
      { key: "import_export:read", label: "View imports", description: "View import/export history" },
      { key: "import_export:write", label: "Run imports", description: "Execute imports and exports" },
    ],
  },
  {
    id: "adoni",
    label: "Adoni AI",
    icon: "Bot",
    permissions: [
      { key: "adoni:chat", label: "Chat with Adoni", description: "Send messages to the AI assistant" },
      { key: "adoni:read_tools", label: "Adoni reads data", description: "Adoni can look up stats, search contacts, view analytics" },
      { key: "adoni:write_tools", label: "Adoni takes actions", description: "Adoni can create tasks, log interactions, send alerts" },
      { key: "adoni:sensitive_data", label: "Adoni shares sensitive data", description: "Adoni reveals financials, strategy, donor details", sensitive: true, minTrust: 3 },
      { key: "adoni:auto_execute", label: "Adoni auto-executes", description: "Adoni can run write actions without confirmation", sensitive: true, minTrust: 4 },
    ],
  },
];

/** Flat list of all permission keys */
export const ALL_PERMISSIONS = PERMISSION_GROUPS.flatMap((g) => g.permissions.map((p) => p.key));

/** Map of permission key -> minTrust */
export const PERMISSION_TRUST_REQUIREMENTS: Record<string, number> = {};
for (const group of PERMISSION_GROUPS) {
  for (const perm of group.permissions) {
    if (perm.minTrust) {
      PERMISSION_TRUST_REQUIREMENTS[perm.key] = perm.minTrust;
    }
  }
}

// ─── Default Role Templates ─────────────────────────────────────────────────
// Seeded into every new campaign. Can be customized per campaign.

export const DEFAULT_ROLE_TEMPLATES: RoleTemplate[] = [
  {
    slug: "super-admin",
    name: "Super Admin",
    description: "Platform owner. Full access to everything.",
    colour: "#dc2626",
    permissions: ["*"],
    isSystem: true,
    trustFloor: 5,
    trustCeiling: 5,
    priority: 0,
  },
  {
    slug: "admin",
    name: "Campaign Admin",
    description: "Full campaign access. Can manage team, billing, and security.",
    colour: "#ea580c",
    permissions: ["*"],
    isSystem: true,
    trustFloor: 4,
    trustCeiling: 5,
    priority: 1,
  },
  {
    slug: "campaign-manager",
    name: "Campaign Manager",
    description: "Day-to-day operations. Everything except billing and security.",
    colour: "#2563eb",
    permissions: [
      "contacts:read", "contacts:write", "contacts:delete", "contacts:export", "contacts:import",
      "canvassing:read", "canvassing:write", "canvassing:manage",
      "gotv:read", "gotv:write", "gotv:manage",
      "volunteers:read", "volunteers:write", "volunteers:manage",
      "team:read", "team:manage",
      "donations:read", "donations:write",
      "budget:read", "budget:write", "budget:manage",
      "email:read", "email:write",
      "sms:read", "sms:write",
      "social:read", "social:write",
      "notifications:write",
      "signs:read", "signs:write",
      "events:read", "events:write",
      "tasks:read", "tasks:write",
      "polls:read", "polls:write",
      "analytics:read", "analytics:export",
      "intelligence:read", "intelligence:write",
      "settings:read", "settings:write",
      "import_export:read", "import_export:write",
      "adoni:chat", "adoni:read_tools", "adoni:write_tools", "adoni:sensitive_data",
    ],
    isSystem: true,
    trustFloor: 3,
    trustCeiling: 5,
    priority: 2,
  },
  {
    slug: "field-director",
    name: "Field Director",
    description: "Canvassing, volunteers, and GOTV operations.",
    colour: "#16a34a",
    permissions: [
      "contacts:read", "contacts:write",
      "canvassing:read", "canvassing:write", "canvassing:manage",
      "gotv:read", "gotv:write", "gotv:manage",
      "volunteers:read", "volunteers:write", "volunteers:manage",
      "team:read",
      "signs:read", "signs:write",
      "events:read", "events:write",
      "tasks:read", "tasks:write",
      "analytics:read",
      "adoni:chat", "adoni:read_tools", "adoni:write_tools",
    ],
    isSystem: true,
    trustFloor: 2,
    trustCeiling: 5,
    priority: 3,
  },
  {
    slug: "finance-officer",
    name: "Finance Officer",
    description: "Donations, budget, receipts, and compliance.",
    colour: "#ca8a04",
    permissions: [
      "donations:read", "donations:write",
      "budget:read", "budget:write", "budget:manage",
      "contacts:read",
      "analytics:read",
      "settings:read",
      "adoni:chat", "adoni:read_tools", "adoni:sensitive_data",
    ],
    isSystem: true,
    trustFloor: 3,
    trustCeiling: 5,
    priority: 4,
  },
  {
    slug: "communications-lead",
    name: "Communications Lead",
    description: "Email, SMS, social media, and public-facing content.",
    colour: "#9333ea",
    permissions: [
      "email:read", "email:write",
      "sms:read", "sms:write",
      "social:read", "social:write",
      "notifications:write",
      "contacts:read",
      "events:read", "events:write",
      "analytics:read",
      "adoni:chat", "adoni:read_tools", "adoni:write_tools",
    ],
    isSystem: true,
    trustFloor: 2,
    trustCeiling: 5,
    priority: 5,
  },
  {
    slug: "volunteer-leader",
    name: "Volunteer Leader",
    description: "Leads a canvass team. Can manage their volunteers.",
    colour: "#0891b2",
    permissions: [
      "contacts:read", "contacts:write",
      "canvassing:read", "canvassing:write",
      "gotv:read",
      "volunteers:read", "volunteers:write",
      "signs:read", "signs:write",
      "tasks:read", "tasks:write",
      "events:read",
      "adoni:chat", "adoni:read_tools",
    ],
    isSystem: true,
    trustFloor: 2,
    trustCeiling: 4,
    priority: 6,
  },
  {
    slug: "canvasser",
    name: "Canvasser",
    description: "Door-to-door canvassing. Sees their turf only.",
    colour: "#059669",
    permissions: [
      "contacts:read",
      "canvassing:read", "canvassing:write",
      "tasks:read",
      "adoni:chat", "adoni:read_tools",
    ],
    isSystem: true,
    trustFloor: 1,
    trustCeiling: 3,
    priority: 7,
  },
  {
    slug: "phone-banker",
    name: "Phone Banker",
    description: "Phone canvassing. Sees call lists only.",
    colour: "#0d9488",
    permissions: [
      "contacts:read",
      "canvassing:read", "canvassing:write",
      "tasks:read",
      "adoni:chat", "adoni:read_tools",
    ],
    isSystem: true,
    trustFloor: 1,
    trustCeiling: 3,
    priority: 8,
  },
  {
    slug: "data-entry",
    name: "Data Entry",
    description: "Contact management and import operations.",
    colour: "#6366f1",
    permissions: [
      "contacts:read", "contacts:write", "contacts:import",
      "import_export:read", "import_export:write",
      "tasks:read",
      "adoni:chat", "adoni:read_tools",
    ],
    isSystem: true,
    trustFloor: 1,
    trustCeiling: 3,
    priority: 9,
  },
  {
    slug: "volunteer",
    name: "Volunteer",
    description: "Basic volunteer. Sees their tasks and assigned work.",
    colour: "#64748b",
    permissions: [
      "contacts:read",
      "canvassing:read",
      "tasks:read",
      "events:read",
      "adoni:chat",
    ],
    isSystem: true,
    trustFloor: 1,
    trustCeiling: 3,
    priority: 10,
  },
  {
    slug: "viewer",
    name: "Viewer",
    description: "Read-only access. Cannot modify any data.",
    colour: "#94a3b8",
    permissions: [
      "contacts:read",
      "analytics:read",
      "events:read",
      "adoni:chat",
    ],
    isSystem: true,
    trustFloor: 1,
    trustCeiling: 2,
    priority: 11,
  },
];

/** Map legacy Prisma Role enum values to new role slugs */
export const LEGACY_ROLE_MAP: Record<string, string> = {
  SUPER_ADMIN: "super-admin",
  ADMIN: "admin",
  CAMPAIGN_MANAGER: "campaign-manager",
  VOLUNTEER_LEADER: "volunteer-leader",
  VOLUNTEER: "volunteer",
  PUBLIC_USER: "viewer",
};
