// Builds Adoni's generated knowledge file from collected training data.
// Output: src/lib/adoni/generated-knowledge.ts (auto-generated, do not edit)

import { collectTrainingData } from "./collect-training-data";
import { writeFileSync } from "fs";
import path from "path";

export async function buildKnowledgeBase(): Promise<void> {
  console.log("[Adoni Training] Collecting training data...");
  const data = await collectTrainingData();

  const output = `// ADONI GENERATED KNOWLEDGE BASE
// AUTO-GENERATED by npm run adoni:train — do not edit manually
// Generated: ${data.generatedAt}

export const GENERATED_KNOWLEDGE = {
  platform: ${JSON.stringify(data.platformCapabilities)},
  apiRoutes: ${JSON.stringify(data.apiRoutes)},
  featureChecklist: ${JSON.stringify(data.featureChecklist)},
  recentFixes: ${JSON.stringify(data.recentBugFixes)},
  electionLaw: ${JSON.stringify(data.electionLaw)},
  generatedAt: ${JSON.stringify(data.generatedAt)},
};

export function getFullKnowledge(): string {
  return [
    "=== PLATFORM STATUS ===",
    GENERATED_KNOWLEDGE.platform,
    "=== API ROUTES ===",
    GENERATED_KNOWLEDGE.apiRoutes,
    "=== FEATURE STATUS ===",
    GENERATED_KNOWLEDGE.featureChecklist,
    "=== RECENT FIXES ===",
    GENERATED_KNOWLEDGE.recentFixes,
    "=== ELECTION LAW ===",
    GENERATED_KNOWLEDGE.electionLaw,
  ].join("\\n\\n");
}
`;

  const outputPath = path.join(process.cwd(), "src/lib/adoni/generated-knowledge.ts");
  writeFileSync(outputPath, output);

  const routeCount = (data.apiRoutes.match(/\n/g) || []).length + 1;
  console.log(`[Adoni Training] Knowledge base built`);
  console.log(`  API routes indexed: ${routeCount}`);
  console.log(`  Output: ${outputPath}`);
}
