#!/usr/bin/env node
/**
 * guard-learn.mjs
 *
 * Reads every push guard history report in .push-guard/history/ and extracts
 * the patterns agents in THIS codebase specifically get wrong — lies they told,
 * warnings the guard caught, logic gaps it found.
 *
 * Writes those patterns to docs/GUARD_KNOWN_PATTERNS.md so every future guard
 * starts with the accumulated knowledge of every guard that ran before it.
 *
 * Run this after any session that produced guard findings worth learning from.
 * Usage: node scripts/guard-learn.mjs
 */

import fs from "node:fs";
import path from "node:path";

const HISTORY_DIR  = ".push-guard/history";
const OUTPUT_FILE  = "docs/GUARD_KNOWN_PATTERNS.md";

function loadHistory() {
  if (!fs.existsSync(HISTORY_DIR)) return [];
  return fs.readdirSync(HISTORY_DIR)
    .filter(f => f.endsWith(".json") && !f.includes("history"))
    .map(f => {
      try { return JSON.parse(fs.readFileSync(path.join(HISTORY_DIR, f), "utf8")); }
      catch { return null; }
    })
    .filter(Boolean);
}

function extractPatterns(history) {
  const lieMap   = new Map(); // normalised claim → { count, examples[] }
  const warnMap  = new Map(); // normalised message → { count, examples[] }

  for (const entry of history) {
    for (const lie of (entry.liesDetected ?? [])) {
      const key = lie.claimed?.toLowerCase().trim() ?? "";
      if (!key) continue;
      if (!lieMap.has(key)) lieMap.set(key, { claimed: lie.claimed, actual: lie.actual, count: 0, dates: [] });
      const rec = lieMap.get(key);
      rec.count++;
      rec.dates.push(entry.pushedAt?.slice(0, 10) ?? "?");
    }
    for (const finding of (entry.findings ?? [])) {
      if (finding.severity !== "WARN" && finding.severity !== "BLOCK") continue;
      const key = finding.message?.toLowerCase().trim() ?? "";
      if (!key) continue;
      if (!warnMap.has(key)) warnMap.set(key, { message: finding.message, severity: finding.severity, count: 0, dates: [] });
      const rec = warnMap.get(key);
      rec.count++;
      rec.dates.push(entry.pushedAt?.slice(0, 10) ?? "?");
    }
  }

  // Sort by frequency — most common lies/warnings first
  const lies  = [...lieMap.values()].sort((a, b) => b.count - a.count);
  const warns = [...warnMap.values()].sort((a, b) => b.count - a.count);
  return { lies, warns, totalPushes: history.length };
}

function buildMarkdown(patterns, history) {
  const { lies, warns, totalPushes } = patterns;
  const now = new Date().toISOString().slice(0, 10);

  const lines = [
    `# Guard Known Patterns`,
    ``,
    `*Auto-generated by \`guard-learn.mjs\` from ${totalPushes} push guard reports.*`,
    `*Last updated: ${now}. Run \`npm run guard:learn\` after any session with new findings.*`,
    ``,
    `These are the patterns that agents in THIS codebase specifically get wrong.`,
    `Every push guard reads this file before starting verification.`,
    `The more pushes accumulate, the smarter this list gets.`,
    ``,
    `---`,
    ``,
  ];

  if (lies.length > 0) {
    lines.push(`## Lies Agents Tell (caught ${lies.reduce((s, l) => s + l.count, 0)}× total)`);
    lines.push(``);
    lines.push(`These are exact claims agents made that were false. Check these first and hardest.`);
    lines.push(``);
    for (const lie of lies) {
      lines.push(`### Caught ${lie.count}× — "${lie.claimed}"`);
      lines.push(`- **What they said:** ${lie.claimed}`);
      lines.push(`- **What was actually true:** ${lie.actual}`);
      lines.push(`- **First seen / last seen:** ${lie.dates[0]} / ${lie.dates[lie.dates.length - 1]}`);
      lines.push(`- **Guard action:** Verify this claim independently. Do not accept it at face value.`);
      lines.push(``);
    }
  } else {
    lines.push(`## Lies Agents Tell`);
    lines.push(``);
    lines.push(`*(None recorded yet — patterns will appear here after guard reports accumulate.)*`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);

  if (warns.length > 0) {
    lines.push(`## Recurring Warnings (${warns.reduce((s, w) => s + w.count, 0)} total findings)`);
    lines.push(``);
    lines.push(`These are issues the guard keeps finding. They are not lies — agents just keep missing them.`);
    lines.push(``);
    for (const warn of warns) {
      lines.push(`### ${warn.severity} — caught ${warn.count}× — "${warn.message}"`);
      lines.push(`- **Pattern:** ${warn.message}`);
      lines.push(`- **Dates:** ${warn.dates.join(", ")}`);
      lines.push(`- **Guard action:** Check this explicitly on every push where it could apply.`);
      lines.push(``);
    }
  } else {
    lines.push(`## Recurring Warnings`);
    lines.push(``);
    lines.push(`*(None recorded yet — patterns will appear here after guard reports accumulate.)*`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`## Seeded Patterns (from incident history — always check these)`);
  lines.push(``);
  lines.push(`These were hardcoded from known incidents before the history log existed.`);
  lines.push(`They are the most reliable patterns in this file.`);
  lines.push(``);
  lines.push(`| What agents claim | What to actually check |`);
  lines.push(`|---|---|`);
  lines.push(`| "Build passes cleanly" | Was it \`tsc --noEmit\` (not enough) or full \`npm run build\` (required)? |`);
  lines.push(`| "Auth is in place" | Read the route file. Does it call \`apiAuth(req)\` or \`getServerSession\` on line 1? |`);
  lines.push(`| "Sidebar entry added" | Open \`src/components/layout/sidebar.tsx\` and look for the href. |`);
  lines.push(`| "GEORGE_TODO updated" | Open \`GEORGE_TODO.md\` and find the checkbox. Do not trust the claim. |`);
  lines.push(`| "CONNECTIONS.md updated" | Open \`CONNECTIONS.md\` and find the specific connection that was added. |`);
  lines.push(`| "Mobile parity checked" | Check \`mobile/\` AND \`mobile-pcs/\` directories. Both exist. |`);
  lines.push(`| "No TypeScript errors" | \`tsc --noEmit\` passing ≠ build passing. Next.js has routing rules tsc does not check. |`);
  lines.push(`| "Feature is wired end-to-end" | Read the API route AND the client component. Both must exist and connect. |`);
  lines.push(`| "deletedAt filter is in place" | Search the query for \`deletedAt: null\`. Missing this returns deleted records silently. |`);
  lines.push(`| "campaignId scoping is in place" | Every DB query touching campaign data must have \`where: { campaignId }\`. |`);
  lines.push(`| "Help tooltips added" | Every FormField must have a \`help\` prop. Open the component and check. |`);
  lines.push(`| "Empty state handled" | Does the component render something useful when the data array is empty? |`);
  lines.push(``);

  return lines.join("\n");
}

const history  = loadHistory();
const patterns = extractPatterns(history);
const markdown = buildMarkdown(patterns, history);

fs.writeFileSync(OUTPUT_FILE, markdown);

console.log(`\nGuard patterns updated: ${OUTPUT_FILE}`);
console.log(`  Pushes analysed  : ${patterns.totalPushes}`);
console.log(`  Lie patterns     : ${patterns.lies.length}`);
console.log(`  Warning patterns : ${patterns.warns.length}`);
console.log(`\nRun again after sessions with new guard findings.\n`);
