// npm run adoni:train — rebuilds Adoni's knowledge base from live system data.
// Run after every feature completion. Also runs nightly via cron.

import { PrismaClient } from "@prisma/client";
import { collectTrainingData } from "../src/lib/adoni/training/collect-training-data";
import { writeFileSync } from "fs";
import path from "path";

const prisma = new PrismaClient();

async function main() {
  console.log("🧠 Starting Adoni training...");

  const data = await collectTrainingData();

  const output = `// ADONI GENERATED KNOWLEDGE BASE
// AUTO-GENERATED by npm run adoni:train — do not edit manually
// Generated: ${data.generatedAt}

export const GENERATED_KNOWLEDGE = {
  platform: ${JSON.stringify(data.platformCapabilities)},
  apiRoutes: ${JSON.stringify(data.apiRoutes)},
  featureChecklist: ${JSON.stringify(data.featureChecklist)},
  recentFixes: ${JSON.stringify(data.recentBugFixes)},
  electionLaw: ${JSON.stringify(data.electionLaw)},
  generatedAt: ${JSON.stringify(data.generatedAt)},
};

export function getFullKnowledge(): string {
  return [
    "=== PLATFORM STATUS ===",
    GENERATED_KNOWLEDGE.platform,
    "=== API ROUTES ===",
    GENERATED_KNOWLEDGE.apiRoutes,
    "=== FEATURE STATUS ===",
    GENERATED_KNOWLEDGE.featureChecklist,
    "=== RECENT FIXES ===",
    GENERATED_KNOWLEDGE.recentFixes,
    "=== ELECTION LAW ===",
    GENERATED_KNOWLEDGE.electionLaw,
  ].join("\\n\\n");
}
`;

  const outputPath = path.join(process.cwd(), "src/lib/adoni/generated-knowledge.ts");
  writeFileSync(outputPath, output);

  const routeCount = (data.apiRoutes.match(/\n/g) || []).length + 1;
  console.log(`✅ Adoni training complete`);
  console.log(`   API routes indexed: ${routeCount}`);
  console.log(`   Platform stats included: contacts, campaigns, officials`);
  console.log(`   Election law: ON/BC/federal 2026`);
  console.log(`   Output: ${outputPath}`);
  console.log(`   Run again after any new feature or article`);
}

main()
  .catch((e) => {
    console.error("❌ Training failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
