/**
 * Canadian electoral data for campaign setup autocomplete.
 * Ontario-first (Oct 2026 municipal elections), with federal + other provinces included.
 */

// ---------------------------------------------------------------------------
// Candidate roles
// ---------------------------------------------------------------------------

const WARD_ROLES = Array.from({ length: 25 }, (_, i) => `Ward ${i + 1} Councillor`);

export const CANDIDATE_ROLES: string[] = [
  // Municipal
  "Mayor",
  "Deputy Mayor",
  "City Councillor",
  ...WARD_ROLES,
  "Regional Councillor",
  "Regional Chair",
  "Township Councillor",
  "Village Councillor",
  "Reeve",
  "Deputy Reeve",
  "Warden",
  "Deputy Warden",
  "School Board Trustee",
  "Public School Board Trustee",
  "Catholic School Board Trustee",
  "French-Language School Board Trustee",
  // Provincial Ontario
  "Member of Provincial Parliament (MPP)",
  // Provincial BC / Alberta / Saskatchewan / Manitoba
  "Member of the Legislative Assembly (MLA)",
  // Provincial Quebec
  "Member of the National Assembly (MNA)",
  // Provincial Newfoundland / Nova Scotia / PEI / NB
  "Member of the House of Assembly (MHA)",
  "Member of the Legislative Assembly of New Brunswick (MLANB)",
  // Federal
  "Member of Parliament (MP)",
];

// ---------------------------------------------------------------------------
// Election types
// ---------------------------------------------------------------------------

export const ELECTION_TYPES: string[] = [
  "Municipal",
  "Provincial",
  "Federal",
  "By-election",
  "School Board",
  "Regional",
];

// ---------------------------------------------------------------------------
// Ontario municipalities
// ---------------------------------------------------------------------------

const ONTARIO_MUNICIPALITIES: string[] = [
  "City of Toronto",
  "City of Ottawa",
  "City of Mississauga",
  "City of Brampton",
  "City of Hamilton",
  "City of London",
  "City of Markham",
  "City of Vaughan",
  "City of Kitchener",
  "City of Windsor",
  "City of Burlington",
  "City of Oakville",
  "City of Richmond Hill",
  "City of Oshawa",
  "City of Barrie",
  "City of Guelph",
  "City of Cambridge",
  "City of Kingston",
  "City of Thunder Bay",
  "City of Greater Sudbury",
  "City of Peterborough",
  "City of North Bay",
  "City of Sault Ste. Marie",
  "City of Brantford",
  "City of St. Catharines",
  "City of Niagara Falls",
  "City of Welland",
  "City of Waterloo",
  "City of Timmins",
  "City of Sarnia",
  "City of Belleville",
  "City of Quinte West",
  "City of Woodstock",
  "City of Cornwall",
  "City of Kenora",
  "Town of Ajax",
  "Town of Aurora",
  "Town of Caledon",
  "Town of Clarington",
  "Town of Collingwood",
  "Town of East Gwillimbury",
  "Town of Georgina",
  "Town of Halton Hills",
  "Town of Innisfil",
  "Town of Midland",
  "Town of Milton",
  "Town of Newmarket",
  "Town of Orangeville",
  "Town of Penetanguishene",
  "Town of Pickering",
  "Town of Whitby",
  "Town of Whitchurch-Stouffville",
  "Township of Brock",
  "Township of King",
  "Township of Scugog",
  "Township of Uxbridge",
  "Municipality of Clarington",
  "Municipality of Trent Hills",
  "Region of Durham",
  "Region of Halton",
  "Region of Peel",
  "Region of Waterloo",
  "Region of York",
  "Niagara Region",
];

// ---------------------------------------------------------------------------
// Ontario provincial ridings (124 ridings, 2022 election map)
// ---------------------------------------------------------------------------

const ONTARIO_PROVINCIAL_RIDINGS: string[] = [
  "Ajax",
  "Algoma-Manitoulin",
  "Barrie-Innisfil",
  "Barrie-Springwater-Oro-Medonte",
  "Bay of Quinte",
  "Beaches-East York",
  "Brampton Centre",
  "Brampton East",
  "Brampton North",
  "Brampton South",
  "Brampton West",
  "Brantford-Brant",
  "Bruce-Grey-Owen Sound",
  "Burlington",
  "Cambridge",
  "Carleton",
  "Chatham-Kent-Leamington",
  "Davenport",
  "Don Valley East",
  "Don Valley North",
  "Don Valley West",
  "Dufferin-Caledon",
  "Durham",
  "Eglinton-Lawrence",
  "Elgin-Middlesex-London",
  "Essex",
  "Etobicoke Centre",
  "Etobicoke-Lakeshore",
  "Etobicoke North",
  "Flamborough-Glanbrook",
  "Glengarry-Prescott-Russell",
  "Guelph",
  "Haldimand-Norfolk",
  "Haliburton-Kawartha Lakes-Brock",
  "Hamilton Centre",
  "Hamilton East-Stoney Creek",
  "Hamilton Mountain",
  "Hamilton West-Ancaster-Dundas",
  "Hastings-Lennox and Addington",
  "Huron-Bruce",
  "Kanata-Carleton",
  "Kingston and the Islands",
  "Kitchener Centre",
  "Kitchener-Conestoga",
  "Kitchener South-Hespeler",
  "Lambton-Kent-Middlesex",
  "Lanark-Frontenac-Kingston",
  "Leeds-Grenville-Thousand Islands and Rideau Lakes",
  "London-Fanshawe",
  "London North Centre",
  "London West",
  "Markham-Stouffville",
  "Markham-Thornhill",
  "Markham-Unionville",
  "Milton",
  "Mississauga Centre",
  "Mississauga East-Cooksville",
  "Mississauga-Erin Mills",
  "Mississauga-Lakeshore",
  "Mississauga-Malton",
  "Mississauga-Streetsville",
  "Nepean",
  "Newmarket-Aurora",
  "Niagara Centre",
  "Niagara Falls",
  "Niagara West",
  "Nickel Belt",
  "Nipissing",
  "Northumberland-Peterborough South",
  "Oak Ridges-Richmond Hill",
  "Oakville",
  "Oakville North-Burlington",
  "Orléans",
  "Oshawa",
  "Ottawa Centre",
  "Ottawa-Vanier",
  "Ottawa West-Nepean",
  "Oxford",
  "Parry Sound-Muskoka",
  "Perth-Wellington",
  "Peterborough-Kawartha",
  "Pickering-Uxbridge",
  "Prince Edward-Hastings",
  "Renfrew-Nipissing-Pembroke",
  "Richmond Hill",
  "Sarnia-Lambton",
  "Sault Ste. Marie",
  "Scarborough-Agincourt",
  "Scarborough Centre",
  "Scarborough-Guildwood",
  "Scarborough North",
  "Scarborough-Rouge Park",
  "Scarborough Southwest",
  "Simcoe-Grey",
  "Simcoe North",
  "Spadina-Fort York",
  "St. Catharines",
  "Stormont-Dundas-South Glengarry",
  "Sudbury",
  "Thornhill",
  "Thunder Bay-Atikokan",
  "Thunder Bay-Superior North",
  "Timiskaming-Cochrane",
  "Timmins",
  "Toronto Centre",
  "Toronto-Danforth",
  "Toronto-St. Paul's",
  "University-Rosedale",
  "Vaughan-Woodbridge",
  "Waterloo",
  "Wellington-Halton Hills",
  "Whitby",
  "Willowdale",
  "Windsor-Tecumseh",
  "Windsor West",
  "York Centre",
  "York-Simcoe",
  "York South-Weston",
];

// ---------------------------------------------------------------------------
// Federal electoral districts (Ontario + key national ridings)
// ---------------------------------------------------------------------------

const FEDERAL_RIDINGS: string[] = [
  // Ontario federal
  "Ajax",
  "Algoma-Manitoulin-Kapuskasing",
  "Aurora-Oak Ridges-Richmond Hill",
  "Barrie-Innisfil",
  "Barrie-Springwater-Oro-Medonte",
  "Bay of Quinte",
  "Beaches-East York",
  "Brampton Centre",
  "Brampton East",
  "Brampton North",
  "Brampton South",
  "Brampton West",
  "Brantford-Brant",
  "Bruce-Grey-Owen Sound",
  "Burlington",
  "Cambridge",
  "Carleton",
  "Chatham-Kent-Leamington",
  "Davenport",
  "Don Valley East",
  "Don Valley North",
  "Don Valley West",
  "Dufferin-Caledon",
  "Durham",
  "Eglinton-Lawrence",
  "Elgin-Middlesex-London",
  "Essex",
  "Etobicoke Centre",
  "Etobicoke-Lakeshore",
  "Etobicoke North",
  "Flamborough-Glanbrook",
  "Glengarry-Prescott-Russell",
  "Guelph",
  "Haldimand-Norfolk",
  "Haliburton-Kawartha Lakes-Brock",
  "Hamilton Centre",
  "Hamilton East-Stoney Creek",
  "Hamilton Mountain",
  "Hamilton West-Ancaster-Dundas",
  "Hastings-Lennox and Addington",
  "Huron-Bruce",
  "Kanata-Carleton",
  "Kenora",
  "Kingston and the Islands",
  "Kitchener Centre",
  "Kitchener-Conestoga",
  "Kitchener South-Hespeler",
  "Lambton-Kent-Middlesex",
  "Lanark-Frontenac-Kingston",
  "Leeds-Grenville-Thousand Islands and Rideau Lakes",
  "London-Fanshawe",
  "London North Centre",
  "London West",
  "Markham-Stouffville",
  "Markham-Thornhill",
  "Markham-Unionville",
  "Milton",
  "Mississauga Centre",
  "Mississauga East-Cooksville",
  "Mississauga-Erin Mills",
  "Mississauga-Lakeshore",
  "Mississauga-Malton",
  "Mississauga-Streetsville",
  "Nepean",
  "Newmarket-Aurora",
  "Niagara Centre",
  "Niagara Falls",
  "Niagara West",
  "Nipissing-Timiskaming",
  "Northumberland-Peterborough South",
  "Oak Ridges-Richmond Hill",
  "Oakville",
  "Oakville North-Burlington",
  "Orléans",
  "Oshawa",
  "Ottawa Centre",
  "Ottawa-Vanier",
  "Ottawa West-Nepean",
  "Oxford",
  "Parry Sound-Muskoka",
  "Perth-Wellington",
  "Peterborough-Kawartha",
  "Pickering-Uxbridge",
  "Prince Edward-Hastings",
  "Renfrew-Nipissing-Pembroke",
  "Richmond Hill",
  "Sarnia-Lambton",
  "Sault Ste. Marie",
  "Scarborough-Agincourt",
  "Scarborough Centre",
  "Scarborough-Guildwood",
  "Scarborough North",
  "Scarborough-Rouge Park",
  "Scarborough Southwest",
  "Simcoe-Grey",
  "Simcoe North",
  "Spadina-Fort York",
  "St. Catharines",
  "Stormont-Dundas-South Glengarry",
  "Sudbury",
  "Thunder Bay-Rainy River",
  "Thunder Bay-Superior North",
  "Timiskaming-Cochrane",
  "Toronto Centre",
  "Toronto-Danforth",
  "Toronto-St. Paul's",
  "University-Rosedale",
  "Vaughan-Woodbridge",
  "Waterloo",
  "Wellington-Halton Hills",
  "Whitby",
  "Willowdale",
  "Windsor-Tecumseh",
  "Windsor West",
  "York Centre",
  "York-Simcoe",
  "York South-Weston",
  // British Columbia
  "Burnaby North-Seymour",
  "Burnaby South",
  "Cariboo-Prince George",
  "Central Okanagan-Similkameen-Nicola",
  "Chilliwack-Hope",
  "Coquitlam-Port Coquitlam",
  "Courtenay-Alberni",
  "Delta-Richmond East",
  "Esquimalt-Saanich-Sooke",
  "Fleetwood-Port Kells",
  "Kamloops-Thompson-Cariboo",
  "Kelowna-Lake Country",
  "Kootenay-Columbia",
  "Langley-Aldergrove",
  "Mission-Matsqui-Abbotsford",
  "Nanaimo-Ladysmith",
  "New Westminster-Burnaby",
  "North Island-Powell River",
  "North Okanagan-Shuswap",
  "North Vancouver",
  "Pitt Meadows-Maple Ridge",
  "Port Moody-Coquitlam",
  "Prince George-Peace River-Northern Rockies",
  "Richmond Centre",
  "Saanich-Gulf Islands",
  "Skeena-Bulkley Valley",
  "South Okanagan-West Kootenay",
  "South Surrey-White Rock",
  "Steveston-Richmond East",
  "Surrey Centre",
  "Surrey-Newton",
  "Vancouver Centre",
  "Vancouver East",
  "Vancouver Granville",
  "Vancouver Kingsway",
  "Vancouver South",
  "Victoria",
  "West Vancouver-Sunshine Coast-Sea to Sky Country",
  // Alberta
  "Airdrie-Rocky View",
  "Battle River-Crowfoot",
  "Bow River",
  "Calgary Centre",
  "Calgary Confederation",
  "Calgary East",
  "Calgary Forest Lawn",
  "Calgary Heritage",
  "Calgary Midnapore",
  "Calgary Nose Hill",
  "Calgary Shepard",
  "Calgary Signal Hill",
  "Calgary Skyview",
  "Calgary West",
  "Edmonton Centre",
  "Edmonton Griesbach",
  "Edmonton Manning",
  "Edmonton Mill Woods",
  "Edmonton Riverbend",
  "Edmonton Southeast",
  "Edmonton Strathcona",
  "Edmonton West",
  "Foothills",
  "Fort McMurray-Cold Lake",
  "Grande Prairie-Mackenzie",
  "Lethbridge",
  "Medicine Hat-Cardston-Warner",
  "Peace River-Westlock",
  "Red Deer-Mountain View",
  "Red Deer-Lacombe",
  "Sherwood Park-Fort Saskatchewan",
  "St. Albert-Edmonton",
  "Yellowhead",
  // Quebec (key ridings)
  "Abitibi-Baie-James-Nunavik-Eeyou",
  "Abitibi-Témiscamingue",
  "Alfred-Pellan",
  "Argenteuil-La Petite-Nation",
  "Beauce",
  "Beauharnois-Salaberry",
  "Brome-Missisquoi",
  "Chambly-Borduas",
  "Châteauguay-Lacolle",
  "Chicoutimi-Le Fjord",
  "Dorval-Lachine-LaSalle",
  "Drummond",
  "Gaspésie-Les Îles-de-la-Madeleine",
  "Hull-Aylmer",
  "Joliette",
  "Jonquière",
  "Lac-Saint-Jean",
  "Laval-Les Îles",
  "Lévis-Lotbinière",
  "Longueuil-Charles-LeMoyne",
  "Longueuil-Saint-Hubert",
  "Marc-Aurèle-Fortin",
  "Mégantic-L'Érable",
  "Mirabel",
  "Mont-Royal",
  "Montarville",
  "Montcalm",
  "Montmagny-L'Islet-Kamouraska-Rivière-du-Loup",
  "Mount Royal",
  "Notre-Dame-de-Grâce-Westmount",
  "Outremont",
  "Papineau",
  "Pierre-Boucher-Les Patriotes-Verchères",
  "Québec",
  "Repentigny",
  "Richmond-Arthabaska",
  "Rimouski-Neigette-Témiscouata-Les Basques",
  "Rivière-des-Mille-Îles",
  "Rivière-du-Nord",
  "Rosemont-La Petite-Patrie",
  "Saint-Hyacinthe-Bagot",
  "Saint-Jean",
  "Saint-Laurent",
  "Saint-Léonard-Saint-Michel",
  "Saint-Maurice-Champlain",
  "Sherbrooke",
  "Shefford",
  "Salaberry-Suroît",
  "Terrebonne",
  "Trois-Rivières",
  "Vimy",
  // Prairies / Atlantic / North
  "Brandon-Souris",
  "Churchill-Keewatinook Aski",
  "Elmwood-Transcona",
  "Kildonan-St. Paul",
  "Portage-Lisgar",
  "Saint Boniface-Saint Vital",
  "Selkirk-Interlake-Eastman",
  "Winnipeg Centre",
  "Winnipeg North",
  "Winnipeg South",
  "Winnipeg South Centre",
  "Moose Jaw-Lake Centre-Lanigan",
  "Prince Albert",
  "Regina-Lewvan",
  "Regina-Qu'Appelle",
  "Saskatoon-University",
  "Saskatoon West",
  "Battlefords-Lloydminster",
  "Halifax",
  "Halifax West",
  "Kings-Hants",
  "Cape Breton-Canso",
  "Fredericton",
  "Moncton-Riverview-Dieppe",
  "Saint John-Rothesay",
  "Charlottetown",
  "Egmont",
  "Malpeque",
  "Cardigan",
  "St. John's East",
  "St. John's South-Mount Pearl",
  "Avalon",
  "Nunavut",
  "Northwest Territories",
  "Yukon",
];

// ---------------------------------------------------------------------------
// Combined jurisdictions list (municipalities + ridings, deduped)
// ---------------------------------------------------------------------------

const _seen = new Set<string>();
export const CANADIAN_JURISDICTIONS: string[] = [
  ...ONTARIO_MUNICIPALITIES,
  ...ONTARIO_PROVINCIAL_RIDINGS,
  ...FEDERAL_RIDINGS,
].filter((item) => {
  if (_seen.has(item)) return false;
  _seen.add(item);
  return true;
});

// ---------------------------------------------------------------------------
// Election type detection from candidate role
// ---------------------------------------------------------------------------

export type ElectionType = "Municipal" | "Provincial" | "Federal";

export function detectElectionType(role: string): ElectionType | null {
  const r = role.toLowerCase();
  if (
    r.includes("mpp") ||
    r.includes("mla") ||
    r.includes("mna") ||
    r.includes("mha") ||
    r.includes("member of provincial") ||
    r.includes("legislative assembly") ||
    r.includes("national assembly") ||
    r.includes("house of assembly")
  )
    return "Provincial";
  // "mp" match — guard against "mpp", "mla" etc.
  if (
    (r === "mp" ||
      r.startsWith("mp ") ||
      r.includes(" mp ") ||
      r.includes("(mp)") ||
      r.includes("member of parliament")) &&
    !r.includes("mpp") &&
    !r.includes("mla") &&
    !r.includes("provincial")
  )
    return "Federal";
  if (
    r.includes("mayor") ||
    r.includes("councillor") ||
    r.includes("ward") ||
    r.includes("reeve") ||
    r.includes("warden") ||
    r.includes("trustee") ||
    r.includes("deputy mayor") ||
    r.includes("regional")
  )
    return "Municipal";
  return null;
}
